create table Stores(name STR);              # Error: Relation already exists
create table People(name NUM, name STR);    # Error: Duplicate attributes found
open table Products                         # Error: Relation does not exist
open table Stores                           # Relation Stores opened successfully
drop table Stores                           # Error: Relation is open
drop table RELATIONCAT                      # Error: This operation is not permitted
close table Stores                          # Relation Stores closed successfully
drop table Stores                           # Relation Stores deleted successfully